version: '3.7'

services:
  app-server:
    container_name: backendContainer
    build:
      context: backend/docker
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on: 
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/softplan?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root     
    networks:
      - backend
      - frontend

  app-client:
      container_name: frontendContainer
      build:
        context: frontend
        dockerfile: Dockerfile
      ports:
        - "80:80" 
      restart: always
      depends_on:
        - app-server
      networks:
        - frontend  

  db:
    container_name: mysqlContainer
    image: mysql:8.0.25
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_DATABASE=softplan
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend  
  
volumes:
  db-data:

networks:
  backend:
  frontend:    