CREATE TABLE PROCESSO_USUARIO (
	CODPROCESSO INT NOT NULL,
	CODUSUARIO INT NOT NULL,
	PRIMARY KEY (CODPROCESSO, CODUSUARIO),
	FOREIGN KEY (CODPROCESSO) REFERENCES PROCESSO(CODPROCESSO),
	FOREIGN KEY (CODUSUARIO) REFERENCES USUARIO(CODUSUARIO)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8