CREATE TABLE USUARIO (
	CODUSUARIO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
	LOGIN VARCHAR(63) NOT NULL,
	SENHA VARCHAR(63) NOT NULL,
	EMAIL VARCHAR(63) NOT NULL,
	PERMISSAO VARCHAR(31) NOT NULL,
	DATAINCLUSAO DATE NOT NULL,
	VERSAO INT
) ENGINE=InnoDB DEFAULT CHARSET=UTF8