CREATE TABLE PROCESSO (
	CODPROCESSO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(63) NOT NULL,
	DESCRICAO VARCHAR(255) NOT NULL,
	STATUS VARCHAR(31) NOT NULL,
	DATAINICIO DATE NOT NULL,
	DATATERMINO DATE,
	CODUSUARIO INT NOT NULL,
	VERSAO INT,
	FOREIGN KEY (CODUSUARIO) REFERENCES USUARIO(CODUSUARIO)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8