CREATE TABLE AUD_PROCESSO (
	REV INT NOT NULL, 
  	REVTYPE INT, 
	CODPROCESSO INT NOT NULL,
	NOME VARCHAR(63),
	DESCRICAO VARCHAR(255),
	STATUS VARCHAR(31),
	DATAINICIO DATE,
	DATATERMINO DATE,
	CODUSUARIO INT,
	VERSAO INT,
	PRIMARY KEY(CODPROCESSO,REV)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8